### PR TITLE
Adding the concept of Upcoming Game in the list

### PR DESCRIPTION
**Pull request by jpcottin**
@lu22do 
What do you think about this feature?
We (the admin) can enter the 48 group phase games in advance as "Future Game". No points are being gained for those games, and the match list will show when they will be instead of the score.

The player will be able to see the upcoming games
The admin will only have to update 2,3 or 4 scores every day, and not enter the whole game

What do you think?

### CODE REVIEW

**Comment by lu22do** [comment]
I don't think I got it. Let's discuss about this feature tomorrow.

**Comment by blackseawave** [comment]
I don't think I got it either.
If you are talking about showing the list of past and upcoming games for informational puposes, it is useful.
But, isn't it already there through:
Matches
- Match list
- New match
- Edit match

-hakan

**Comment by jpcottin** [comment]
screen shot 2018-06-03 at 4 21 18 pm

I'm not sure if you don't get the code or the initial explanation of this missing feature

- The user will be able to see the list of the games
- the admin doesn't have to enter a game setting 3 times a day , just the scores, this will ease the operational  aspect

**Review by lu22do — APPROVED** [review]
LGTM

**Pull request merged**
